server:
  port: 9090
spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:analyzer
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true`
        
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
